name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch: # This allows you to start the build manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🗑 Clean Old Android Folder
        run: rm -rf android

      - name: 🔨 Build Prebuild
        run: npx expo prebuild --platform android --clean

      - name: 🤖 Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quit-smoke-apk
          path: android/app/build/outputs/apk/release/*.apk
